house/urls.py
# urls.py
from unicodedata import name

from django.urls import path
from house.views import HouseList, HouseResidentsList

urlpatterns = [
    path('house/all/', HouseList.as_view(), name='houses'),
    path('house/<int:pk>/', HouseResidentsList.as_view(), name='house'),
]

test_derevianko/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('house.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

house/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Model, CharField, IntegerField, PositiveIntegerField


class House(Model):
    address = CharField(max_length=255, blank=False, null=False)
    residence_count = PositiveIntegerField(blank=False, null=False)
    year_of_construction = IntegerField(blank=False,
                                        null=False,
                                        validators=[MinValueValidator(1900),
                                                    MaxValueValidator(2020)]
                                        )

resident/models.py
from django.db import models
from django.db.models import Model, CharField, DateField, IntegerField, PositiveIntegerField, ForeignKey


class Resident(Model):
    full_name = CharField(max_length=255, blank=False, null=False)
    date_of_birth = DateField(blank=False, null=False)
    room_number = PositiveIntegerField(blank=False, null=False)
    house = ForeignKey('house.House', on_delete=models.CASCADE)

house/views.py
from django.views.generic import ListView, DetailView

from house.models import House


class HouseList(ListView):
    model = House
    template_name = 'house_list.html'

    def get_queryset(self):
        order_by = self.request.GET.get('order_by')
        ordering = self.request.GET.get('ordering')

        prefix = '-' if ordering == 'descending' else ''

        qs = super(HouseList, self).get_queryset()

        try:
            if order_by:
                qs = qs.order_by(prefix + order_by)
        except:
            raise
        return qs


class HouseResidentsList(DetailView):
    model = House
    template_name = 'house_resident_list.html'

resident/views.py
from django.shortcuts import render
from django.views.generic import ListView


# class ResidentList(ListView):

house/templates/house_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}"/>

<h1>List of all houses</h1>

<form method="GET" action="{% url 'houses' %}">
    Sort by:
    <select name="order_by">
        <option value="address">Address</option>
        <option value="residence_count">Residence total count</option>
        <option value="year_of_construction">Year of construction</option>
    </select>

    <select name="ordering">
        <option value="ascending">Ascending</option>
        <option value="descending">Descending</option>
    </select>
    <button>
        Sort
    </button>
</form>

<table class="table">
    {% if object_list %}
        <tr>
            <th>ID:</th>
            <th>Address:</th>
            <th>Residence total count:</th>
            <th>Year of construction:</th>
            <th></th>
        </tr>
        {% for house in object_list %}
            <tr>
                <td>{{ house.id }}</td>
                <td>{{ house.address }}</td>
                <td>{{ house.residence_count }}</td>
                <td>{{ house.year_of_construction }}</td>
                <td>
                    <a href="{% url 'house' house.id %}">
                        <button>Residents</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <h3>No houses here :(</h3>
    {% endif %}
</table>

house/templates/house_resident_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}"/>

<h1>Resident list of house {{ object.id }}</h1>

<table class="table">
    {% if object.resident_set.all %}
        <tr>
            <th>Full name:</th>
            <th>Date of birth:</th>
            <th>Room number:</th>
        </tr>
        {% for resident in object.resident_set.all %}
            <tr>
                <td>{{ resident.full_name }}</td>
                <td>{{ resident.date_of_birth }}</td>
                <td>{{ resident.room_number }}</td>
            </tr>

        {% endfor %}
    {% else %}
        <h3>No residents here :(</h3>
    {% endif %}
</table>
<br>
<a href="{% url 'houses' %}">
    <button>See all houses</button>
</a>